# Generated by Django 4.2.1 on 2023-06-28 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='captoion',
            new_name='caption',
        ),
    ]
